#!/usr/bin/env python3
"""Build the FY2025/26 dataset in the published dashboard's own schema.

The live 'Noon P&L Performance' page carries one year as `const DATA = {...}`.
This writes a second year in exactly that shape so the two can sit side by side
behind a fiscal-year switch.

It reads the financial model directly rather than going through the dashboard
input workbook, because the published page is generated by a different
pipeline and its schema is the one that has to be matched.

Conventions taken from the live page so the two years read alike:
  · working capital counts other current assets and other current liabilities
    only — trade payables, credit cards and other payables sit outside it
  · the P&L stops at EBITDA, with operating expenses as a single line
  · collections and payments are derived from the movement in the balances
  · ageing and counterparty detail are left empty; they are not in the model

FY2025/26 has no budget — there is none to hold a closed year against — so the
comparison series is FY2024/25 actual, and `meta.comparator` says so.
"""
import datetime, json, sys

import openpyxl

M = 1_000_000.0
CUR = (18, 29, 30)      # FY25/26 months and year total on 02_Consolidated_FS
PRI = (5, 16, 17)       # FY24/25

BU = [(10, "Tracks"), (11, "Government Schools (legacy)"), (12, "Government Schools (new)"),
      (13, "B2B"), (14, "KSA B2C"), (15, "Other global businesses")]
OFF_COS, OFF_MKT = 9, 19

R = dict(rev=9, cos=18, gp=25, mkt=28, cm=35, opx=38, ebitda=45,
         cash=63, ar=64, other_ca=65, ap=69, defrev=71, other_cl=73,
         cf_op=99, cf_inv=103, cf_fin=108)


def main(path="v47.xlsx", out="fy2526_page.json"):
    wb = openpyxl.load_workbook(path, data_only=True)
    cs = wb["02_Consolidated_FS"]

    hdr = cs.cell(5, CUR[0]).value
    if not isinstance(hdr, datetime.datetime) or (hdr.year, hdr.month) != (2025, 7):
        sys.exit(f"expected Jul-2025 at column {CUR[0]}, found {hdr!r} — the model's "
                 "columns have moved.")

    def ser(row, span, sign=1.0):
        return [round(sign * (cs.cell(row, c).value or 0) / M, 4)
                for c in range(span[0], span[1] + 1)]

    labels = [cs.cell(5, c).value.strftime("%b-%y") for c in range(CUR[0], CUR[1] + 1)]
    months = [l.split("-")[0] for l in labels]
    N, LAST = 12, 11

    def blk(a, b):
        return {"actual": round(a, 4), "budget": round(b, 4),
                "var": round(a - b, 4), "pct": round(a / b, 6) if b else None}

    def line(name, row, cost, sign=1.0, total=False):
        a, b = ser(row, CUR, sign), ser(row, PRI, sign)
        return {"name": name, "cost": cost, "total": total,
                "monthly": {"actual": a, "budget": b},
                "month": blk(a[LAST], b[LAST]), "ytd": blk(sum(a), sum(b))}

    # ── revenue and costs ───────────────────────────────────────────────────
    revenue = [line(n, r, False) for r, n in BU]
    revenue.append(line("Total revenue", R["rev"], False, total=True))
    tot_from_bu = sum(x["ytd"]["actual"] for x in revenue[:-1])
    if abs(tot_from_bu - revenue[-1]["ytd"]["actual"]) > 0.01:
        sys.exit(f"business units sum to {tot_from_bu:,.2f}M but Total Revenues reads "
                 f"{revenue[-1]['ytd']['actual']:,.2f}M.")

    costs = [line("Direct costs", R["cos"], True),
             line("Marketing", R["mkt"], True),
             line("Operating expenses", R["opx"], True)]
    tc_a = [round(sum(c["monthly"]["actual"][i] for c in costs), 4) for i in range(N)]
    tc_b = [round(sum(c["monthly"]["budget"][i] for c in costs), 4) for i in range(N)]
    costs.append({"name": "Total costs", "cost": True, "total": True,
                  "monthly": {"actual": tc_a, "budget": tc_b},
                  "month": blk(tc_a[LAST], tc_b[LAST]), "ytd": blk(sum(tc_a), sum(tc_b))})

    # ── P&L, every subtotal derived so the table always adds up ────────────
    def combine(base, less, name):
        a = [round(base["monthly"]["actual"][i] - sum(m["monthly"]["actual"][i] for m in less), 4)
             for i in range(N)]
        b = [round(base["monthly"]["budget"][i] - sum(m["monthly"]["budget"][i] for m in less), 4)
             for i in range(N)]
        return {"name": name, "kind": "value", "cost": False, "total": True,
                "monthly": {"actual": a, "budget": b},
                "month": blk(a[LAST], b[LAST]), "ytd": blk(sum(a), sum(b))}

    rev = dict(revenue[-1], name="Revenue", kind="value", total=False)
    dc  = dict(costs[0], kind="value")
    mk  = dict(costs[1], name="Marketing expense", kind="value")
    ox  = dict(costs[2], kind="value")
    gp  = combine(rev, [dc], "Gross profit")
    cp  = combine(gp,  [mk], "Contribution profit")
    eb  = combine(cp,  [ox], "EBITDA")

    def pct_row(name, num):
        def r(p):
            return {"actual": num[p]["actual"] / rev[p]["actual"] if rev[p]["actual"] else None,
                    "budget": num[p]["budget"] / rev[p]["budget"] if rev[p]["budget"] else None}
        return {"name": name, "kind": "pct", "cost": False, "total": False,
                "month": r("month"), "ytd": r("ytd")}

    pl = [rev, dc, gp, pct_row("Gross profit margin", gp), mk, cp,
          pct_row("Contribution margin", cp), ox, eb, pct_row("EBITDA margin", eb)]

    # ── revenue mix ─────────────────────────────────────────────────────────
    tm = rev["month"]["actual"] or 1
    ty = rev["ytd"]["actual"] or 1
    rev_mix = [{"name": r["name"],
                "month": {"rev": r["month"]["actual"], "share": r["month"]["actual"] / tm},
                "ytd":   {"rev": r["ytd"]["actual"],   "share": r["ytd"]["actual"] / ty}}
               for r in revenue[:-1]]

    # ── P&L by business unit, both years ───────────────────────────────────
    def yr(row, span):
        v = cs.cell(row, span[2]).value
        return round((v or 0) / M, 4)

    def unit(row, span):
        rv, cos, mkt = yr(row, span), yr(row + OFF_COS, span), yr(row + OFF_MKT, span)
        if rv == 0 and cos == 0 and mkt == 0:
            return None
        g, c = rv - cos, rv - cos - mkt
        return {"rev": rv, "cos": cos, "mkt": mkt,
                "gp": round(g, 4), "gp_pct": g / rv if rv else None,
                "cp": round(c, 4), "cp_pct": c / rv if rv else None}

    bu_pl = [{"name": n, "cur": unit(r, CUR), "pri": unit(r, PRI)} for r, n in BU]

    def roll(key):
        out = {}
        for k in ("rev", "cos", "mkt"):
            out[k] = round(sum((b[key] or {}).get(k, 0) for b in bu_pl), 4)
        out["gp"] = round(out["rev"] - out["cos"], 4)
        out["gp_pct"] = out["gp"] / out["rev"] if out["rev"] else None
        out["cp"] = round(out["gp"] - out["mkt"], 4)
        out["cp_pct"] = out["cp"] / out["rev"] if out["rev"] else None
        return out

    bu_pl.append({"name": "Total", "cur": roll("cur"), "pri": roll("pri"), "total": True})
    if abs(bu_pl[-1]["cur"]["rev"] - rev["ytd"]["actual"]) > 0.01:
        sys.exit("the business-unit table does not tie to total revenue.")

    # ── working capital ─────────────────────────────────────────────────────
    ar_b   = ser(R["ar"], CUR)
    ap_b   = ser(R["ap"], CUR, -1)
    dfr_b  = ser(R["defrev"], CUR, -1)
    oca    = ser(R["other_ca"], CUR)
    ocl    = ser(R["other_cl"], CUR, -1)
    other  = [round(a + b, 4) for a, b in zip(oca, ocl)]
    nwc    = [round(ar_b[i] + ap_b[i] + dfr_b[i] + other[i], 4) for i in range(N)]
    wc_monthly = [{"month": labels[i], "ar": ar_b[i], "ap": ap_b[i], "deferred": dfr_b[i],
                   "other": other[i], "nwc": nwc[i],
                   "movement": 0 if i == 0 else round(nwc[i] - nwc[i-1], 4),
                   "forecast": False} for i in range(N)]

    op_ar, op_ap = ser(R["ar"], PRI)[-1], ser(R["ap"], PRI, -1)[-1]
    op_dfr, op_oca, op_ocl = (ser(R["defrev"], PRI, -1)[-1], ser(R["other_ca"], PRI)[-1],
                              ser(R["other_cl"], PRI, -1)[-1])

    def wc_item(name, o, c):
        return {"item": name, "open": round(o, 4), "close": round(c, 4),
                "movement": round(c - o, 4), "cash_impact": round(-(c - o), 4)}

    wc_ytd = [wc_item("Accounts receivable", op_ar, ar_b[-1]),
              wc_item("Accounts payable", op_ap, ap_b[-1]),
              wc_item("Deferred revenue", op_dfr, dfr_b[-1]),
              wc_item("Other current assets", op_oca, oca[-1]),
              wc_item("Other current liabilities", op_ocl, ocl[-1])]
    wc_ytd.append(wc_item("Net working capital",
                          op_ar + op_ap + op_dfr + op_oca + op_ocl, nwc[-1]))

    # ── receivables and payables, rolled forward off the balance sheet ─────
    inv = rev["monthly"]["actual"]
    pur = [round(costs[0]["monthly"]["actual"][i] + costs[2]["monthly"]["actual"][i], 4)
           for i in range(N)]

    def rollfwd(open0, closes, adds):
        opens = [open0] + closes[:-1]
        flows = [round(opens[i] + adds[i] - closes[i], 4) for i in range(N)]
        return opens, flows

    ar_open, coll = rollfwd(op_ar, ar_b, inv)
    ap_open, pay = rollfwd(-op_ap, [-v for v in ap_b], pur)

    ar_monthly = [{"month": labels[i], "opening": ar_open[i], "invoiced": inv[i],
                   "collected": coll[i], "closing": ar_b[i],
                   "rate": round(coll[i] / inv[i], 4) if inv[i] else None} for i in range(N)]
    ap_monthly = [{"month": labels[i], "opening": ap_open[i], "purchases": pur[i],
                   "payments": pay[i], "closing": -ap_b[i],
                   "dpo": round(-ap_b[i] / pur[i] * 30.4, 4) if pur[i] else None}
                  for i in range(N)]
    ar_ytd = {"invoiced": round(sum(inv), 4), "collected": round(sum(coll), 4),
              "closing": ar_b[-1], "rate": round(sum(coll) / sum(inv), 4) if sum(inv) else None}
    ap_ytd = {"purchases": round(sum(pur), 4), "payments": round(sum(pay), 4),
              "closing": -ap_b[-1], "dpo": ap_monthly[-1]["dpo"]}

    # ── cash ────────────────────────────────────────────────────────────────
    bal = ser(R["cash"], CUR)
    op_cash = ser(R["cash"], PRI)[-1]
    opens = [op_cash] + bal[:-1]
    cf_op, cf_inv, cf_fin = ser(R["cf_op"], CUR), ser(R["cf_inv"], CUR), ser(R["cf_fin"], CUR)
    resid = [round((bal[i] - opens[i]) - (cf_op[i] + cf_inv[i] + cf_fin[i]), 4) for i in range(N)]

    def bridge(o, a, i_, f, x, c):
        steps, run = [{"step": "Opening cash", "kind": "total", "value": round(o, 4)}], o
        for nm, v in (("Operating cash flow", a), ("Investing cash flow", i_),
                      ("Financing cash flow", f), ("FX & other movements", x)):
            run += v
            steps.append({"step": nm, "kind": "delta", "value": round(v, 4),
                          "running": round(run, 4)})
        steps.append({"step": "Closing cash", "kind": "total", "value": round(c, 4)})
        return steps

    bridge_month = bridge(opens[LAST], cf_op[LAST], cf_inv[LAST], cf_fin[LAST],
                          resid[LAST], bal[LAST])
    bridge_ytd = bridge(op_cash, sum(cf_op), sum(cf_inv), sum(cf_fin), sum(resid), bal[-1])
    for b in (bridge_month, bridge_ytd):
        if abs(b[-2]["running"] - b[-1]["value"]) > 0.01:
            sys.exit("the cash bridge does not close on the balance-sheet cash line.")

    net = [round(bal[i] - opens[i], 4) for i in range(N)]
    burn3 = sum(net[-3:]) / 3
    runway = {"burn_month": net[LAST], "burn_3m": round(burn3, 4),
              "ytd_move": round(bal[-1] - op_cash, 4),
              "months": round(bal[-1] / -burn3, 2) if burn3 < 0 else None}

    prior_lbl = [cs.cell(5, c).value.strftime("%b-%y") for c in range(PRI[1] - 5, PRI[1] + 1)]
    prior_val = [round((cs.cell(R["cash"], c).value or 0) / M, 4)
                 for c in range(PRI[1] - 5, PRI[1] + 1)]
    cash_monthly = {"labels": prior_lbl + labels, "values": prior_val + bal,
                    "illustrative": [False] * (len(prior_lbl) + N),
                    "forecast": [False] * (len(prior_lbl) + N)}

    cash_tiles = {
        "month": {"cash": {"value": bal[LAST], "note": ""},
                  "collections": {"value": coll[LAST],
                                  "note": "derived from revenue and the movement in receivables"}},
        "ytd":   {"cash": {"value": bal[-1], "note": ""},
                  "collections": {"value": round(sum(coll), 4), "note": "derived"}},
    }

    # ── commentary, generated from the figures above ───────────────────────
    big = max(bu_pl[:-1], key=lambda b: (b["cur"] or {}).get("rev", 0))
    pri_rev = revenue[-1]["ytd"]["budget"]
    key_updates = [
        ("Revenue", f"FY2025/26 revenue of ${rev['ytd']['actual']:,.2f}M came in "
                    f"{(rev['ytd']['actual']-pri_rev)/pri_rev:+.1%} on FY2024/25's ${pri_rev:,.2f}M — "
                    f"essentially flat year on year. {big['name']} was the largest unit at "
                    f"${big['cur']['rev']:,.2f}M, {big['cur']['rev']/rev['ytd']['actual']:.0%} of the total."),
        ("Margin", f"Gross profit of ${gp['ytd']['actual']:,.2f}M gave a "
                   f"{gp['ytd']['actual']/rev['ytd']['actual']:.1%} margin, against "
                   f"{gp['ytd']['budget']/pri_rev:.1%} last year. After ${mk['ytd']['actual']:,.2f}M of "
                   f"marketing, contribution was ${cp['ytd']['actual']:,.2f}M, a "
                   f"{cp['ytd']['actual']/rev['ytd']['actual']:.1%} margin."),
        ("EBITDA", f"EBITDA of ${eb['ytd']['actual']:,.2f}M is a "
                   f"{eb['ytd']['actual']/rev['ytd']['actual']:.1%} margin, against "
                   f"{eb['ytd']['budget']/pri_rev:.1%} last year, after ${ox['ytd']['actual']:,.2f}M of "
                   f"operating expenses. The year closed with all twelve months booked."),
        ("Costs", f"Direct costs of ${dc['ytd']['actual']:,.2f}M ran at "
                  f"{dc['ytd']['actual']/rev['ytd']['actual']:.0%} of revenue and operating expenses at "
                  f"{ox['ytd']['actual']/rev['ytd']['actual']:.0%}. Total costs of "
                  f"${costs[-1]['ytd']['actual']:,.2f}M were "
                  f"{(costs[-1]['ytd']['actual']-costs[-1]['ytd']['budget'])/costs[-1]['ytd']['budget']:+.1%} "
                  f"on last year."),
        ("Working capital", f"Receivables closed at ${ar_b[-1]:,.2f}M against ${op_ar:,.2f}M at the start "
                            f"of the year, on derived collections of ${sum(coll):,.2f}M. Payables closed at "
                            f"${-ap_b[-1]:,.2f}M against ${-op_ap:,.2f}M."),
        ("Cash", f"Cash closed the year at ${bal[-1]:,.2f}M against ${op_cash:,.2f}M at the start, up "
                 f"${bal[-1]-op_cash:,.2f}M. Operations and investing together consumed "
                 f"${abs(sum(cf_op)+sum(cf_inv)):,.2f}M; financing contributed ${sum(cf_fin):,.2f}M, so the "
                 f"closing balance is funded by drawdown rather than by trading."),
    ]

    data = {
        "meta": {"period": "June 2026", "ytd_label": "Jul 2025 – Jun 2026",
                 "generated": datetime.date.today().strftime("%d %b %Y"),
                 "source": "Noon financial model 3.0 v47.xlsx", "currency": "USD M",
                 "months": months, "month_labels": labels, "year": 2025,
                 "period_index": LAST, "fy_start_month": 7, "fiscal_year": "FY2025/26",
                 "fy_open_label": labels[0], "opex_split": False,
                 "comparator": "FY24/25", "closed": True},
        "revenue": revenue, "costs": costs, "pl": pl, "rev_mix": rev_mix,
        "bu_pl": bu_pl, "bu_pl_meta": {"cur_label": "FY25/26", "pri_label": "FY24/25"},
        "wc_monthly": wc_monthly, "wc_ytd": wc_ytd,
        "ar_monthly": ar_monthly, "ar_ytd": ar_ytd,
        "ap_monthly": ap_monthly, "ap_ytd": ap_ytd,
        "ar_aging": [], "ar_aging_total": None, "ap_aging": [], "ap_aging_total": None,
        "ar_by_contract": [], "ap_by_vendor": [],
        "cash_tiles": cash_tiles, "bridge_month": bridge_month, "bridge_ytd": bridge_ytd,
        "cash_monthly": cash_monthly, "runway": runway,
        "key_updates": [{"topic": t, "text": x} for t, x in key_updates],
    }
    with open(out, "w") as f:
        json.dump(data, f, ensure_ascii=False, separators=(",", ":"))

    print(f"  FY2025/26  {labels[0]} – {labels[-1]} (closed)")
    print(f"  Revenue    ${rev['ytd']['actual']:,.2f}M   prior year ${pri_rev:,.2f}M")
    print(f"  Gross      ${gp['ytd']['actual']:,.2f}M   {gp['ytd']['actual']/rev['ytd']['actual']:.1%}")
    print(f"  EBITDA     ${eb['ytd']['actual']:,.2f}M   {eb['ytd']['actual']/rev['ytd']['actual']:.1%}")
    print(f"  Cash       ${bal[-1]:,.2f}M closing, from ${op_cash:,.2f}M")
    print(f"  Wrote      {out}")


if __name__ == "__main__":
    main(*sys.argv[1:])
